// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dsp_sampler
void dsp_sampler(Rcpp::NumericMatrix U);
RcppExport SEXP dspBayes_dsp_sampler(SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type U(USEXP);
    dsp_sampler(U);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"dspBayes_dsp_sampler", (DL_FUNC) &dspBayes_dsp_sampler, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dspBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
