// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dsp_
Rcpp::List dsp_(Rcpp::NumericMatrix u_rcpp, Rcpp::IntegerVector x_rcpp, Rcpp::List w_day_blocks, Rcpp::IntegerVector w_to_days_idx, Rcpp::IntegerVector w_cyc_to_subj_idx, Rcpp::List subj_day_blocks, Rcpp::IntegerVector day_to_subj_idx, Rcpp::List gamma_specs, Rcpp::NumericVector phi_specs, Rcpp::IntegerVector x_miss, Rcpp::IntegerVector sex_miss_to_w, Rcpp::List sex_miss_info, Rcpp::NumericVector utau_rcpp, Rcpp::List tau_coefs, Rcpp::List u_miss_info, Rcpp::IntegerVector u_miss_type, Rcpp::IntegerVector u_preg_map, Rcpp::IntegerVector u_sex_map, int fw_len, int n_burn, int n_samp);
RcppExport SEXP _dspBayes_dsp_(SEXP u_rcppSEXP, SEXP x_rcppSEXP, SEXP w_day_blocksSEXP, SEXP w_to_days_idxSEXP, SEXP w_cyc_to_subj_idxSEXP, SEXP subj_day_blocksSEXP, SEXP day_to_subj_idxSEXP, SEXP gamma_specsSEXP, SEXP phi_specsSEXP, SEXP x_missSEXP, SEXP sex_miss_to_wSEXP, SEXP sex_miss_infoSEXP, SEXP utau_rcppSEXP, SEXP tau_coefsSEXP, SEXP u_miss_infoSEXP, SEXP u_miss_typeSEXP, SEXP u_preg_mapSEXP, SEXP u_sex_mapSEXP, SEXP fw_lenSEXP, SEXP n_burnSEXP, SEXP n_sampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type u_rcpp(u_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x_rcpp(x_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type w_day_blocks(w_day_blocksSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type w_to_days_idx(w_to_days_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type w_cyc_to_subj_idx(w_cyc_to_subj_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type subj_day_blocks(subj_day_blocksSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type day_to_subj_idx(day_to_subj_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type gamma_specs(gamma_specsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type phi_specs(phi_specsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x_miss(x_missSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sex_miss_to_w(sex_miss_to_wSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type sex_miss_info(sex_miss_infoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type utau_rcpp(utau_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tau_coefs(tau_coefsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type u_miss_info(u_miss_infoSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type u_miss_type(u_miss_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type u_preg_map(u_preg_mapSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type u_sex_map(u_sex_mapSEXP);
    Rcpp::traits::input_parameter< int >::type fw_len(fw_lenSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    rcpp_result_gen = Rcpp::wrap(dsp_(u_rcpp, x_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_subj_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, x_miss, sex_miss_to_w, utau_rcpp, tau_coefs, u_miss_info, u_miss_type, u_preg_map, u_sex_map, fw_len, n_burn, n_samp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dspBayes_dsp_", (DL_FUNC) &_dspBayes_dsp_, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_dspBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
