# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsp_ <- function(U_rcpp, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_subj_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, x_miss_cyc, x_miss_day, utau_rcpp, tau_coefs, u_miss_info, u_miss_type, u_preg_map, u_sex_map, fw_len, n_burn, n_samp) {
    .Call('_dspBayes_dsp_', PACKAGE = 'dspBayes', U_rcpp, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_subj_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, x_miss_cyc, x_miss_day, utau_rcpp, tau_coefs, u_miss_info, u_miss_type, u_preg_map, u_sex_map, fw_len, n_burn, n_samp)
}

utest_cpp_ <- function(U, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_subj_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, x_miss_cyc, x_miss_day, utau_rcpp, tau_coefs, fw_len, n_burn, n_samp, test_data) {
    .Call('_dspBayes_utest_cpp_', PACKAGE = 'dspBayes', U, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_subj_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, x_miss_cyc, x_miss_day, utau_rcpp, tau_coefs, fw_len, n_burn, n_samp, test_data)
}

