# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsp_sampler <- function(U, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_cyc_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, fw_len, n_burn, n_samp) {
    .Call('_dspBayes_dsp_sampler', PACKAGE = 'dspBayes', U, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_cyc_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, fw_len, n_burn, n_samp)
}

utest_cpp_ <- function(U, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_cyc_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, fw_len, n_burn, n_samp) {
    .Call('_dspBayes_utest_cpp_', PACKAGE = 'dspBayes', U, X_rcpp, w_day_blocks, w_to_days_idx, w_cyc_to_cyc_idx, subj_day_blocks, day_to_subj_idx, gamma_specs, phi_specs, fw_len, n_burn, n_samp)
}

